const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY="fleetpilot.v1",today=()=>new Date().toISOString().slice(0,10),uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2);
const addDays=(d,n)=>{const x=new Date(d+"T12:00:00");x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
const seed={settings:{name:"Мой автопарк",currency:"PLN"},cars:[
{id:"1",brand:"Toyota",model:"Prius",year:2018,plate:"WA 1234A",driver:"Александр",status:"active",mileage:245620,oilInterval:10000,lastOil:240000,insurance:addDays(today(),90),inspection:addDays(today(),180),image:"",history:[{date:today(),value:245620}]},
{id:"2",brand:"Skoda",model:"Octavia",year:2020,plate:"WZ 5678K",driver:"Иван",status:"active",mileage:178900,oilInterval:15000,lastOil:165000,insurance:addDays(today(),18),inspection:addDays(today(),40),image:"",history:[{date:today(),value:178900}]},
{id:"3",brand:"Toyota",model:"Auris Hybrid",year:2015,plate:"WW 9012P",driver:"",status:"repair",mileage:312400,oilInterval:10000,lastOil:302000,insurance:addDays(today(),220),inspection:addDays(today(),-3),image:"",history:[{date:today(),value:312400}]}],
repairs:[{id:"r1",carId:"1",title:"Замена масла и фильтров",date:addDays(today(),7),mileage:250000,budget:420,status:"planned",note:"Масло 0W-20"},{id:"r2",carId:"2",title:"Передние тормозные колодки",date:addDays(today(),3),mileage:180000,budget:850,status:"service",note:"Проверить диски"}],
finances:[{id:"f1",carId:"1",type:"income",amount:4860,date:today(),week:"2026-W31",note:"Доход за неделю"},{id:"f2",carId:"1",type:"repair",amount:320,date:today(),week:"2026-W31",note:"Ремонт"},{id:"f3",carId:"2",type:"income",amount:5120,date:today(),week:"2026-W31",note:"Доход за неделю"}]};
let db=JSON.parse(localStorage.getItem(KEY)||"null")||structuredClone(seed),selected=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(db)),car=id=>db.cars.find(x=>x.id===id),oil=c=>c.lastOil+c.oilInterval-c.mileage,days=d=>Math.ceil((new Date(d+"T12:00:00")-new Date(today()+"T12:00:00"))/86400000);
const money=v=>new Intl.NumberFormat("pl-PL",{style:"currency",currency:db.settings.currency,maximumFractionDigits:0}).format(v||0),km=v=>new Intl.NumberFormat("ru-RU").format(v||0)+" км",date=d=>new Date(d+"T12:00:00").toLocaleDateString("ru-RU");
function toast(t){$("#toast").textContent=t;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),1600)}
function show(id){$$(".page").forEach(x=>x.classList.toggle("active",x.id===id));$$("nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===id));$("#pageTitle").textContent={fleetPage:"Автопарк",repairsPage:"Ремонты",financePage:"Финансы",documentsPage:"Документы",settingsPage:"Настройки",carPage:"Автомобиль"}[id];if(id==="fleetPage")renderFleet();if(id==="repairsPage")renderRepairs();if(id==="financePage")renderFinance();if(id==="documentsPage")renderDocuments();if(id==="settingsPage")renderSettings()}
function need(c){return oil(c)<=1000||days(c.insurance)<=30||days(c.inspection)<=30}
function renderFleet(){const q=$("#search").value.toLowerCase(),f=$("#filter").value;const list=db.cars.filter(c=>(`${c.brand} ${c.model} ${c.plate} ${c.driver}`).toLowerCase().includes(q)&&(f==="all"||(f==="attention"?need(c):c.status===f)));$("#summary").innerHTML=[["Всего",db.cars.length],["На линии",db.cars.filter(x=>x.status==="active").length],["В ремонте",db.cars.filter(x=>x.status==="repair").length],["Свободно",db.cars.filter(x=>x.status==="free").length],["Внимание",db.cars.filter(need).length]].map(x=>`<div class="sum"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join("");$("#fleet").innerHTML=list.map(c=>{const o=oil(c),i=days(c.insurance),t=days(c.inspection);return `<article class="car"><div class="photo" style="${c.image?`background-image:url('${c.image}')`:""}"><div><h3>${c.brand} ${c.model}</h3><span>${c.plate} · ${c.year}</span></div></div><div class="body"><div class="metrics"><div class="metric"><small>Пробег</small><strong>${km(c.mileage)}</strong></div><div class="metric ${o<=0?"bad":o<=1000?"warn":""}"><small>До масла</small><strong>${o<=0?"Просрочено":km(o)}</strong></div><div class="metric ${i<=30?"warn":""}"><small>Страховка</small><strong>${i} дн.</strong></div><div class="metric ${t<0?"bad":t<=30?"warn":""}"><small>Техосмотр</small><strong>${t<0?"Просрочен":t+" дн."}</strong></div></div><div class="actions"><button onclick="openMileage('${c.id}')">+ Пробег</button><button class="primary" onclick="openCar('${c.id}')">Открыть</button></div></div></article>`}).join("")}
function renderRepairs(){$("#repairs").innerHTML=[...db.repairs].sort((a,b)=>a.date.localeCompare(b.date)).map(r=>{const c=car(r.carId);return `<div class="row"><div class="row-top"><div><h3>${r.title}</h3><p>${c.brand} ${c.model} · ${c.plate}</p></div><strong>${money(r.budget)}</strong></div><p>📅 ${date(r.date)} ${r.mileage?" · "+km(r.mileage):""} · ${r.status}</p><p>${r.note||""}</p></div>`}).join("")||"Нет ремонтов"}
function totals(list){const inc=list.filter(x=>x.type==="income").reduce((s,x)=>s+Number(x.amount),0),exp=list.filter(x=>x.type!=="income").reduce((s,x)=>s+Number(x.amount),0);return{inc,exp,profit:inc-exp}}
function renderFinance(){const t=totals(db.finances);$("#financeSummary").innerHTML=[["Доход",money(t.inc)],["Расходы",money(t.exp)],["Прибыль",money(t.profit)]].map(x=>`<div class="sum"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join("");$("#finance").innerHTML=[...db.finances].sort((a,b)=>b.date.localeCompare(a.date)).map(f=>{const c=car(f.carId);return `<div class="row"><div class="row-top"><div><h3>${f.note||f.type}</h3><p>${c.brand} ${c.model} · ${c.plate} · ${date(f.date)}</p></div><strong>${f.type==="income"?"+":"-"}${money(f.amount)}</strong></div></div>`}).join("")}
function renderDocuments(){$("#documents").innerHTML=db.cars.map(c=>`<div class="card"><h3>${c.brand} ${c.model}</h3><p>${c.plate}</p><p>Страховка до: <strong>${date(c.insurance)}</strong></p><p>Техосмотр до: <strong>${date(c.inspection)}</strong></p></div>`).join("")}
function renderSettings(){$("#fleetName").value=db.settings.name;$("#currency").value=db.settings.currency}
function options(sel=""){return db.cars.map(c=>`<option value="${c.id}" ${c.id===sel?"selected":""}>${c.brand} ${c.model} · ${c.plate}</option>`).join("")}
window.openMileage=id=>{const c=car(id);$("#mileageCarId").value=id;$("#newMileage").value=c.mileage;$("#mileageDate").value=today();$("#mileageInfo").textContent=`${c.brand} ${c.model} · текущий ${km(c.mileage)} · до масла ${km(Math.max(0,oil(c)))}`;$("#mileageDialog").showModal()}
window.openCar=id=>{selected=id;const c=car(id),f=db.finances.filter(x=>x.carId===id),t=totals(f),r=db.repairs.filter(x=>x.carId===id);show("carPage");$("#carDetail").innerHTML=`<div class="card"><h2>${c.brand} ${c.model}</h2><p>${c.plate} · ${c.year} · ${c.driver||"Без водителя"}</p><div class="metrics"><div class="metric"><small>Пробег</small><strong>${km(c.mileage)}</strong></div><div class="metric"><small>До масла</small><strong>${km(Math.max(0,oil(c)))}</strong></div><div class="metric"><small>Страховка</small><strong>${date(c.insurance)}</strong></div><div class="metric"><small>Техосмотр</small><strong>${date(c.inspection)}</strong></div></div><button onclick="openMileage('${c.id}')" class="full">+ Пробег</button><button onclick="openRepair('${c.id}')" class="full">+ План ремонта</button><button onclick="openFinance('${c.id}')" class="full">+ Доход / расход</button></div><div class="card"><h3>Финансы</h3><p>Доход: ${money(t.inc)}</p><p>Расходы: ${money(t.exp)}</p><p>Прибыль: ${money(t.profit)}</p></div><div class="card"><h3>Ремонты</h3>${r.map(x=>`<p>${date(x.date)} · ${x.title} · ${money(x.budget)}</p>`).join("")||"Нет ремонтов"}</div>`}
function openCarDialog(c){$("#carId").value=c?.id||"";$("#brand").value=c?.brand||"";$("#model").value=c?.model||"";$("#year").value=c?.year||new Date().getFullYear();$("#plate").value=c?.plate||"";$("#driver").value=c?.driver||"";$("#status").value=c?.status||"active";$("#mileage").value=c?.mileage||0;$("#oilInterval").value=c?.oilInterval||10000;$("#lastOil").value=c?.lastOil||0;$("#insurance").value=c?.insurance||addDays(today(),365);$("#inspection").value=c?.inspection||addDays(today(),365);$("#image").value=c?.image||"";$("#carDialog").showModal()}
window.openRepair=id=>{$("#repairCar").innerHTML=options(id);$("#repairDate").value=today();$("#repairDialog").showModal()}
window.openFinance=id=>{$("#financeCar").innerHTML=options(id);$("#financeDate").value=today();$("#financeDialog").showModal()}
$("#carForm").onsubmit=e=>{e.preventDefault();const id=$("#carId").value||uid(),old=car(id),obj={id,brand:$("#brand").value,model:$("#model").value,year:Number($("#year").value),plate:$("#plate").value,driver:$("#driver").value,status:$("#status").value,mileage:Number($("#mileage").value),oilInterval:Number($("#oilInterval").value),lastOil:Number($("#lastOil").value),insurance:$("#insurance").value,inspection:$("#inspection").value,image:$("#image").value,history:old?.history||[{date:today(),value:Number($("#mileage").value)}]};old?Object.assign(old,obj):db.cars.push(obj);save();$("#carDialog").close();renderFleet();toast("Автомобиль сохранён")}
$("#mileageForm").onsubmit=e=>{e.preventDefault();const c=car($("#mileageCarId").value),v=Number($("#newMileage").value);if(v<c.mileage)return toast("Пробег не может быть меньше");c.mileage=v;c.history.push({date:$("#mileageDate").value,value:v});save();$("#mileageDialog").close();selected===c.id?openCar(c.id):renderFleet();toast("Пробег обновлён")}
$("#repairForm").onsubmit=e=>{e.preventDefault();db.repairs.push({id:uid(),carId:$("#repairCar").value,title:$("#repairTitle").value,date:$("#repairDate").value,mileage:Number($("#repairMileage").value||0),budget:Number($("#repairBudget").value||0),status:$("#repairStatus").value,note:$("#repairNote").value});save();$("#repairDialog").close();renderRepairs();toast("Ремонт добавлен")}
$("#financeForm").onsubmit=e=>{e.preventDefault();db.finances.push({id:uid(),carId:$("#financeCar").value,type:$("#financeType").value,amount:Number($("#financeAmount").value),date:$("#financeDate").value,week:$("#financeWeek").value,note:$("#financeNote").value});save();$("#financeDialog").close();renderFinance();toast("Запись добавлена")}
$$("nav button").forEach(b=>b.onclick=()=>show(b.dataset.page));$$("[data-close]").forEach(b=>b.onclick=()=>$("#"+b.dataset.close).close());$("#addCar").onclick=()=>openCarDialog();$("#addRepair").onclick=()=>openRepair("");$("#addFinance").onclick=()=>openFinance("");$("#back").onclick=()=>show("fleetPage");$("#search").oninput=renderFleet;$("#filter").onchange=renderFleet;$("#saveSettings").onclick=()=>{db.settings.name=$("#fleetName").value;db.settings.currency=$("#currency").value;save();toast("Сохранено")};$("#exportData").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:"application/json"}));a.download="fleetpilot.json";a.click()};$("#importData").onchange=async e=>{try{db=JSON.parse(await e.target.files[0].text());save();show("fleetPage");toast("Импортировано")}catch{toast("Ошибка импорта")}};$("#resetData").onclick=()=>{if(confirm("Сбросить всё?")){db=structuredClone(seed);save();show("fleetPage")}};show("fleetPage");