window.FLEETPILOT_CLOUD_CONFIG = Object.freeze({
  url: "https://tbpfasumklpdqwnlfncd.supabase.co",
  publishableKey: "sb_publishable_Y8lMZQN7Fc7V2HAixaZZrA_w-7STzMh",
  ownerEmail: "balyshevy@gmail.com",
  redirectUrl: "https://fleetpilot.balyshevy.workers.dev/?email-confirmed=1",
  dashboardUrl: "https://supabase.com/dashboard/project/tbpfasumklpdqwnlfncd"
});
(()=>{const supabase=window.supabase;if(!supabase?.createClient||supabase.createClient.__fleetPilotSingleton)return;const nativeCreate=supabase.createClient.bind(supabase);let sharedClient=null,sharedUrl='',sharedKey='';const create=function(url,key,options){const u=String(url||''),k=String(key||'');if(sharedClient&&u===sharedUrl&&k===sharedKey)return sharedClient;if(sharedClient&&u!==sharedUrl){console.warn('FleetPilot blocked a second Supabase project client in the same page',u);return sharedClient}sharedClient=nativeCreate(url,key,options);sharedUrl=u;sharedKey=k;window.__FLEETPILOT_SUPABASE_CLIENT__=sharedClient;return sharedClient};create.__fleetPilotSingleton=true;create.__nativeCreateClient=nativeCreate;supabase.createClient=create})();

/* Role gate: desktop keeps common CRM; mechanic gets service-only desktop content and GPS. */
(()=>{
 const mobile=()=>window.matchMedia?.('(max-width:1099px)').matches;
 document.documentElement.classList.add('fp-role-shell-gate');
 const style=document.createElement('style');style.setAttribute('data-role-shell-preboot','1');style.textContent='html.fp-role-shell-gate body>.app,html.fp-driver-booting body>.app,html.fp-mechanic-booting body>.app{visibility:hidden!important;pointer-events:none!important}html.fp-driver-booting body>.ambient-background,html.fp-mechanic-booting body>.ambient-background{display:none!important}html.fp-driver-booting body:before,html.fp-mechanic-booting body:before{content:"FleetPilot";position:fixed;inset:0;display:grid;place-items:center;background:#f3f5f8;color:#101828;font:800 20px system-ui;z-index:899998}html.fp-driver-booting body:after,html.fp-mechanic-booting body:after{content:"";position:fixed;left:50%;top:55%;width:28px;height:28px;margin:-14px;border:3px solid #d0d5dd;border-top-color:#101828;border-radius:50%;animation:fpBootSpin .8s linear infinite;z-index:899999}@media(min-width:1100px){html.fp-mechanic-desktop #desktopCommandKpis,html.fp-mechanic-desktop .control-center-grid>[data-control-window="tasks"],html.fp-mechanic-desktop .control-center-grid>[data-control-window="efficiency"],html.fp-mechanic-desktop .control-center-grid>[data-control-window="activity"],html.fp-mechanic-desktop .desktop-command-side,html.fp-mechanic-desktop .today-hero,html.fp-mechanic-desktop .owner-dashboard,html.fp-mechanic-desktop .intelligence-grid,html.fp-mechanic-desktop .week-plan,html.fp-mechanic-desktop #healthSummary,html.fp-mechanic-desktop #fleetSummary{display:none!important}html.fp-mechanic-desktop .control-center-grid{grid-template-columns:1fr!important}html.fp-mechanic-desktop .control-center-grid>[data-control-window="gps"]{display:block!important}}';document.head.appendChild(style);
 const ensureAssets=(kind,version)=>{const key=kind==='driver'?'DriverApp':'MechanicApp';if(!document.querySelector(`link[data-${kind}-app-css]`)){const l=document.createElement('link');l.rel='stylesheet';l.href=`${kind}-app/app.css?v=${version}`;l.setAttribute(`data-${kind}-app-css`,'1');document.head.appendChild(l)}if(window.FleetPilot?.[key])return Promise.resolve();const existing=document.querySelector(`script[data-${kind}-app]`);if(existing)return new Promise(r=>existing.addEventListener('load',r,{once:true}));return new Promise(resolve=>{const s=document.createElement('script');s.src=`${kind}-app/app.js?v=${version}`;s.async=false;s.setAttribute(`data-${kind}-app`,'1');s.onload=resolve;s.onerror=resolve;document.body.appendChild(s)})};
 const setDesktopRole=role=>document.documentElement.classList.toggle('fp-mechanic-desktop',role==='mechanic'&&!mobile());
 window.addEventListener('fleetpilot:access-ready',async event=>{const role=String(event.detail?.role||window.FleetPilotCloud?.role||'').toLowerCase();setDesktopRole(role);
  if(role==='driver'){document.documentElement.classList.remove('fp-mechanic-booting');document.documentElement.classList.add('fp-driver-booting');await ensureAssets('driver','210005');window.FleetPilot?.DriverApp?.mount?.();document.documentElement.classList.remove('fp-role-shell-gate');return}
  if(role==='mechanic'&&mobile()){document.documentElement.classList.remove('fp-driver-booting');document.documentElement.classList.add('fp-mechanic-booting');await ensureAssets('mechanic','210009');window.FleetPilot?.MechanicApp?.mount?.();document.documentElement.classList.remove('fp-role-shell-gate');return}
  window.FleetPilot?.MechanicApp?.unmount?.();document.documentElement.classList.remove('fp-role-shell-gate','fp-driver-booting','fp-mechanic-booting');
 },{capture:true});
 window.addEventListener('resize',()=>{const role=String(window.FleetPilotCloud?.role||'').toLowerCase();setDesktopRole(role);if(!mobile()&&role==='mechanic'){window.FleetPilot?.MechanicApp?.unmount?.();document.documentElement.classList.remove('fp-role-shell-gate','fp-mechanic-booting')}});
})();

function fpLegacyBootShim(){try{if(typeof FLEETPILOT_ROUTES==='object')FLEETPILOT_ROUTES.driversPage='drivers';if(typeof FLEETPILOT_ROUTE_PAGES==='object')FLEETPILOT_ROUTE_PAGES.drivers='driversPage';if(typeof forceInitialFleetRender==='function'){const renderOnly=function(){if(window.innerWidth<1100||!document.querySelector('#fleetPage')?.classList.contains('active'))return;try{renderFleet?.()}catch{}try{renderDesktopCommandKpis?.()}catch{}try{renderDesktopEvents?.()}catch{}try{renderDesktopInsights?.()}catch{}try{renderControlCenterExtras?.()}catch{}try{fleetPilotBootCompleted=true}catch{}};try{forceInitialFleetRender=renderOnly}catch{}window.forceInitialFleetRender=renderOnly}if(typeof scheduleInitialFleetBoot==='function'){const schedule=function(){if(window.innerWidth<1100||!document.querySelector('#fleetPage')?.classList.contains('active'))return;requestAnimationFrame(()=>window.forceInitialFleetRender?.())};try{scheduleInitialFleetBoot=schedule}catch{}window.scheduleInitialFleetBoot=schedule}}catch(error){console.warn('FleetPilot legacy boot shim',error)}}
document.addEventListener('DOMContentLoaded',fpLegacyBootShim,{once:true});window.addEventListener('fleetpilot:access-ready',fpLegacyBootShim);
window.addEventListener('load',()=>{const load=(attr,src)=>new Promise(resolve=>{if(document.querySelector(`script[${attr}]`))return resolve();const s=document.createElement('script');s.src=src;s.setAttribute(attr,'1');s.async=false;s.onload=resolve;s.onerror=()=>{console.error('FleetPilot module load failed',src);resolve()};document.body.appendChild(s)});const css=(attr,href)=>{if(document.querySelector(`link[${attr}]`))return;const l=document.createElement('link');l.rel='stylesheet';l.href=href;l.setAttribute(attr,'1');document.head.appendChild(l)};(async()=>{await load('data-fp20-core','modules/core/runtime.js?v=200002');await load('data-fp20-router','modules/router/router.js?v=200001');await load('data-fp20-boot','modules/core/boot.js?v=200001');await load('data-fp20-fleet-status','modules/fleet/status.js?v=200001');await load('data-fp20-driver-state','modules/drivers/state.js?v=200001');await load('data-fp20-fleet-board','modules/fleet/board.js?v=200003');await load('data-fp20-driver-assignment','modules/drivers/assignment.js?v=200001');await load('data-fp20-mileage','modules/fleet/mileage.js?v=200001');await load('data-fp20-ui-completion','modules/ui/completion.js?v=200001');await load('data-fp-critical-consistency','fp-critical-consistency-hotfix.js?v=20260811');await load('data-fp-v19-expense-service','modules/finance/expense-service-v19-behavior.js?v=200001');css('data-driver-app-css','driver-app/app.css?v=210005');await load('data-driver-app','driver-app/app.js?v=210005');css('data-mechanic-app-css','mechanic-app/app.css?v=210009');await load('data-mechanic-app','mechanic-app/app.js?v=210009');await load('data-fp-live-permissions','modules/roles/live-permissions.js?v=210004');await load('data-fp-invite-password','modules/auth/invite-password-flow.js?v=210006');window.dispatchEvent(new CustomEvent('fleetpilot:modules-ready',{detail:{version:'21.0.0-mechanic-desktop-kpi'}}));try{window.FleetPilot?.FleetBoard?.render?.()}catch{}})();},{once:true});