/* FleetPilot Mechanic Workspace — isolated service shell backed by shared fleet DB */
(()=>{'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const FP=window.FleetPilot=window.FleetPilot||{};let mounted=false,tab='home',filter='';
function role(){try{return typeof window.enterpriseCurrentRole==='function'?String(window.enterpriseCurrentRole()||'').toLowerCase():String(window.FleetPilotCloud?.role||document.body?.dataset?.enterpriseRole||'').toLowerCase()}catch{return''}}
function isMechanic(){return role()==='mechanic'}
function isMobile(){return window.matchMedia?.('(max-width:1099px)').matches}
function data(){const db=window.db||window.getFleetPilotDatabase?.()||{};return{db,cars:Array.isArray(db.cars)?db.cars.filter(c=>!c.archived&&!c.deletedAt):[],repairs:Array.isArray(db.repairs)?db.repairs.filter(r=>!r.deletedAt):[],requests:Array.isArray(db.driverRepairRequests)?db.driverRepairRequests.filter(r=>!r.deletedAt):[]}}
function carBy(id,d=data()){return d.cars.find(c=>String(c.id)===String(id))}
function model(c){try{return window.model?.(c)||{brand:c?.brand||'',model:c?.model||''}}catch{return{brand:c?.brand||'',model:c?.model||''}}}
function statusText(s){try{return window.repairStatusText?.(s)||s}catch{return s||'Без статуса'}}
function activeRepair(r){return !['done','cancelled','rejected','archived','closed'].includes(String(r.status||'').toLowerCase())}
function name(){const c=window.FleetPilotCloud||{},p=c.profile||{};return p.display_name||p.full_name||p.name||c.session?.user?.email||'Механик'}
function fmtDate(v,withTime=false){if(!v)return'Дата не указана';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return d.toLocaleString('ru-RU',withTime?{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}:{day:'2-digit',month:'2-digit',year:'numeric'})}
function carTitle(c){const m=model(c);return `${m.brand||'Автомобиль'} ${m.model||''}`.trim()}
function driverName(c){return c?.tenant||c?.driverName||c?.driver_name||'Без водителя'}
function repairCreated(r){return r.createdAt||r.created_at||r.reportedAt||r.reported_at||r.date||''}
function requestCreated(r){return r.createdAt||r.created_at||r.submittedAt||r.submitted_at||r.date||''}
function kpis(d){const a=d.repairs.filter(activeRepair);return{active:a.length,repair:a.filter(r=>r.status==='repair').length,service:a.filter(r=>r.status==='service').length,parts:a.filter(r=>r.status==='parts').length,newReq:d.requests.filter(r=>['new','accepted'].includes(String(r.status||'').toLowerCase())).length,done:d.repairs.filter(r=>r.status==='done').length}}
function workCard(r,d){const c=carBy(r.carId||r.car_id||r.vehicleId,d),m=model(c),next=window.serviceNextStatusLabel?.(r.status);return `<article class="ma-work-card">
 <div class="ma-work-car"><div><span class="ma-plate">${esc(c?.plate||'Без номера')}</span><h3>${esc(carTitle(c))}</h3><p>${esc(c?.city||'Город не указан')} · ${esc(driverName(c))}</p></div><span class="ma-chip ${esc(r.status||'planned')}">${esc(statusText(r.status))}</span></div>
 <div class="ma-work-main"><small>Работа</small><strong>${esc(r.title||'Сервисная работа')}</strong><p>${esc(r.problem||r.note||r.service||'Описание не указано')}</p></div>
 <div class="ma-meta-grid"><div><span>Создано</span><strong>${esc(fmtDate(repairCreated(r),true))}</strong></div><div><span>Пробег</span><strong>${Number(r.mileage||c?.mileage||0).toLocaleString('ru-RU')} км</strong></div><div><span>Сервис</span><strong>${esc(r.service||'Не указан')}</strong></div><div><span>Исполнитель</span><strong>${esc(r.mechanic||'Не назначен')}</strong></div></div>
 <div class="ma-actions"><button data-ma-open-repair="${esc(r.id)}">Открыть карточку</button>${activeRepair(r)&&next?`<button class="primary" data-ma-next="${esc(r.id)}">${esc(next)}</button>`:''}</div>
 </article>`}
function requestCard(r,d){const c=carBy(r.car_id||r.carId||r.vehicleId,d),label=(window.DRIVER_REPAIR_CATEGORY_LABELS||{})[r.category]||r.category||'Заявка';return `<article class="ma-work-card request-card">
 <div class="ma-work-car"><div><span class="ma-plate">${esc(c?.plate||'Без автомобиля')}</span><h3>${esc(carTitle(c))}</h3><p>${esc(c?.city||'Город не указан')} · ${esc(driverName(c))}</p></div><span class="ma-chip request">${esc((window.DRIVER_REPAIR_STATUS_LABELS||{})[r.status]||r.status||'Новая')}</span></div>
 <div class="ma-work-main"><small>Заявка водителя</small><strong>${esc(label)}</strong><p>${esc(r.description||'Описание не указано')}</p></div>
 <div class="ma-meta-grid"><div><span>Сообщено</span><strong>${esc(fmtDate(requestCreated(r),true))}</strong></div><div><span>Пробег</span><strong>${Number(r.mileage||0).toLocaleString('ru-RU')} км</strong></div><div><span>Водитель</span><strong>${esc(r.driver_name||r.driverName||r.driver_email||driverName(c))}</strong></div><div><span>Категория</span><strong>${esc(label)}</strong></div></div>
 <div class="ma-actions"><button class="primary" data-ma-request="${esc(r.id)}">Открыть заявку</button></div>
 </article>`}
function home(d){const k=kpis(d),active=d.repairs.filter(activeRepair).sort((a,b)=>Date.parse(repairCreated(b)||0)-Date.parse(repairCreated(a)||0)).slice(0,4),req=d.requests.filter(r=>['new','accepted'].includes(String(r.status||'').toLowerCase())).sort((a,b)=>Date.parse(requestCreated(b)||0)-Date.parse(requestCreated(a)||0)).slice(0,3);return `<header class="ma-head"><div><small>Сервисный отдел</small><h1>Здравствуйте, ${esc(name())}</h1><p>Здесь только актуальные сервисные задачи и заявки.</p></div><button data-ma-tab="profile" class="ma-avatar">🔧</button></header><section class="ma-kpis"><button data-ma-tab="queue"><span>Активные</span><strong>${k.active}</strong></button><button data-ma-filter="repair"><span>В ремонте</span><strong>${k.repair}</strong></button><button data-ma-filter="service"><span>Ждут сервис</span><strong>${k.service}</strong></button><button data-ma-filter="parts"><span>Ждут детали</span><strong>${k.parts}</strong></button><button data-ma-tab="requests"><span>Заявки</span><strong>${k.newReq}</strong></button><button data-ma-filter="done"><span>Выполнено</span><strong>${k.done}</strong></button></section><section class="ma-section-head"><div><small>Сейчас в работе</small><h2>Текущие работы</h2></div><button data-ma-tab="queue">Все работы</button></section>${active.length?active.map(r=>workCard(r,d)).join(''):`<div class="ma-empty ma-card">Активных работ нет</div>`}${req.length?`<section class="ma-section-head"><div><small>Новые сообщения</small><h2>Заявки водителей</h2></div><button data-ma-tab="requests">Все заявки</button></section>${req.map(r=>requestCard(r,d)).join('')}`:''}`}
function queue(d,f=''){let rows=d.repairs.filter(r=>f==='done'?r.status==='done':activeRepair(r));if(f&&f!=='done')rows=rows.filter(r=>r.status===f);rows.sort((a,b)=>Date.parse(repairCreated(b)||0)-Date.parse(repairCreated(a)||0));return `<div class="ma-page-head"><div><small>Рабочая очередь</small><h1>${f?esc(statusText(f)):'Все работы'}</h1><p>${rows.length} записей · автомобиль всегда указан первым</p></div><button data-ma-action="new-repair">+ Задача</button></div>${rows.length?rows.map(r=>workCard(r,d)).join(''):`<div class="ma-empty ma-card">Записей нет</div>`}`}
function requests(d){const rows=d.requests.filter(r=>!['rejected','cancelled','archived','done'].includes(String(r.status||'').toLowerCase())).sort((a,b)=>Date.parse(requestCreated(b)||0)-Date.parse(requestCreated(a)||0)).slice(0,50);return `<div class="ma-page-head"><div><small>От водителей</small><h1>Заявки</h1><p>Сначала новые, в каждой карточке видно авто, водителя и время сообщения.</p></div></div>${rows.length?rows.map(r=>requestCard(r,d)).join(''):`<div class="ma-empty ma-card">Новых заявок нет</div>`}`}
function cars(d){const active=d.repairs.filter(activeRepair);const ids=new Set(active.map(r=>String(r.carId||r.car_id||r.vehicleId)));const rows=d.cars.filter(c=>ids.has(String(c.id))).sort((a,b)=>carTitle(a).localeCompare(carTitle(b)));return `<div class="ma-page-head"><div><small>Автомобили</small><h1>Машины в сервисе</h1><p>Только автомобили с активными сервисными работами.</p></div></div><section class="ma-grid">${rows.length?rows.map(c=>{const m=model(c),works=active.filter(r=>String(r.carId||r.car_id||r.vehicleId)===String(c.id)).sort((a,b)=>Date.parse(repairCreated(b)||0)-Date.parse(repairCreated(a)||0)),latest=works[0];return `<article class="ma-car-card"><div class="ma-car-card-top"><div><span class="ma-plate">${esc(c.plate||'Без номера')}</span><h2>${esc(m.brand)} ${esc(m.model)}</h2><p>${esc(c.city||'Город не указан')} · ${esc(driverName(c))}</p></div><span class="ma-chip ${esc(latest?.status||'planned')}">${esc(statusText(latest?.status))}</span></div><div class="ma-car-stats"><div><span>Активных работ</span><strong>${works.length}</strong></div><div><span>Пробег</span><strong>${Number(c.mileage||latest?.mileage||0).toLocaleString('ru-RU')} км</strong></div></div><div class="ma-car-latest"><small>Последняя работа</small><strong>${esc(latest?.title||'—')}</strong><span>${esc(fmtDate(repairCreated(latest),true))}</span></div><button data-ma-open-car="${esc(c.id)}">Открыть автомобиль</button></article>`}).join(''):`<div class="ma-empty ma-card">Сейчас машин в сервисе нет</div>`}</section>`}
function calendar(d){const rows=d.repairs.filter(r=>r.date).sort((a,b)=>String(a.date).localeCompare(String(b.date))).slice(0,40);return `<div class="ma-page-head"><div><small>План</small><h1>Календарь сервиса</h1><p>Работы по датам с автомобилем и текущим статусом.</p></div></div><section class="ma-card ma-calendar-list">${rows.length?rows.map(r=>{const c=carBy(r.carId||r.car_id||r.vehicleId,d);return `<article class="ma-calendar-row"><time>${esc(fmtDate(r.date))}</time><div><strong>${esc(r.title||'Работа')}</strong><small>${esc(c?.plate||'Без номера')} · ${esc(carTitle(c))}</small></div><span class="ma-chip ${esc(r.status||'planned')}">${esc(statusText(r.status))}</span></article>`}).join(''):`<div class="ma-empty">Запланированных работ нет</div>`}</section>`}
function profile(d){const k=kpis(d),cloud=window.FleetPilotCloud||{};return `<div class="ma-profile"><div class="ma-profile-avatar">🔧</div><h1>${esc(name())}</h1><p>${esc(cloud.session?.user?.email||'')}</p><span>Механик</span></div><section class="ma-card"><div class="ma-profile-grid"><div><small>Компания</small><strong>${esc(cloud.workspace?.name||'—')}</strong></div><div><small>Город</small><strong>${esc(cloud.membership?.city||cloud.workspace?.city||'—')}</strong></div><div><small>Активных работ</small><strong>${k.active}</strong></div><div><small>Новых заявок</small><strong>${k.newReq}</strong></div></div></section><section class="ma-card ma-menu"><button data-ma-action="password">🔐 <span><strong>Безопасность</strong><small>Изменить пароль</small></span></button><button data-ma-action="logout">↪ <span><strong>Выйти</strong><small>Завершить сеанс</small></span></button></section>`}
function render(){if(!mounted)return;const root=$('#fleetPilotMechanicApp');if(!root)return;const d=data();const body=tab==='home'?home(d):tab==='queue'?queue(d,filter):tab==='requests'?requests(d):tab==='cars'?cars(d):tab==='calendar'?calendar(d):profile(d);root.innerHTML=`<aside class="ma-nav"><div class="ma-brand"><b>F</b><span>FleetPilot<small>Сервис</small></span></div><nav><button class="${tab==='home'?'active':''}" data-ma-tab="home">⌂ <span>Главная</span></button><button class="${tab==='queue'?'active':''}" data-ma-tab="queue">🔧 <span>Работы</span></button><button class="${tab==='requests'?'active':''}" data-ma-tab="requests">☷ <span>Заявки</span></button><button class="${tab==='cars'?'active':''}" data-ma-tab="cars">🚗 <span>Автомобили</span></button><button class="${tab==='calendar'?'active':''}" data-ma-tab="calendar">□ <span>Календарь</span></button><button class="${tab==='profile'?'active':''}" data-ma-tab="profile">◎ <span>Профиль</span></button></nav></aside><main class="ma-content">${body}</main>`}
function mount(){if(!isMechanic()||!isMobile())return false;let root=$('#fleetPilotMechanicApp');if(!root){root=document.createElement('div');root.id='fleetPilotMechanicApp';document.body.appendChild(root)}document.documentElement.classList.add('fp-mechanic-app');mounted=true;render();return true}
function unmount(){document.documentElement.classList.remove('fp-mechanic-app');$('#fleetPilotMechanicApp')?.remove();mounted=false}
function sync(){isMechanic()&&isMobile()?mount():unmount()}
document.addEventListener('click',e=>{const t=e.target.closest('[data-ma-tab]');if(t){tab=t.dataset.maTab;filter='';render();return}const f=e.target.closest('[data-ma-filter]');if(f){tab='queue';filter=f.dataset.maFilter;render();return}const rid=e.target.closest('[data-ma-open-repair]')?.dataset.maOpenRepair;if(rid){window.editRepair?.(rid);return}const next=e.target.closest('[data-ma-next]')?.dataset.maNext;if(next){window.advanceServiceRepair?.(next);render();return}const req=e.target.closest('[data-ma-request]')?.dataset.maRequest;if(req){window.openRepairFromFleetRequest?.(req);return}const car=e.target.closest('[data-ma-open-car]')?.dataset.maOpenCar;if(car){window.openCar?.(car,'service');return}const a=e.target.closest('[data-ma-action]')?.dataset.maAction;if(a==='new-repair')window.openRepairDialog?.();if(a==='password')document.getElementById('changePasswordDialog')?.showModal?.();if(a==='logout')window.FleetPilotCloud?.signOut?.()});
['fleetpilot:access-ready','fleetpilot:modules-ready','fleetpilot:repair-requests-changed','fleetpilot:assignments-changed'].forEach(n=>window.addEventListener(n,()=>setTimeout(()=>{sync();if(mounted)render()},0)));window.addEventListener('resize',sync);window.addEventListener('pageshow',()=>setTimeout(sync,0));setTimeout(sync,300);FP.MechanicApp={mount,render,sync,unmount};})();