/* FleetPilot Mechanic Workspace — isolated service shell backed by shared fleet DB */
(()=>{'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const FP=window.FleetPilot=window.FleetPilot||{};let mounted=false,tab='home';
function role(){try{return typeof window.enterpriseCurrentRole==='function'?String(window.enterpriseCurrentRole()||'').toLowerCase():String(window.FleetPilotCloud?.role||document.body?.dataset?.enterpriseRole||'').toLowerCase()}catch{return''}}
function isMechanic(){return role()==='mechanic'}
function data(){const db=window.db||window.getFleetPilotDatabase?.()||{};return{db,cars:Array.isArray(db.cars)?db.cars.filter(c=>!c.archived&&!c.deletedAt):[],repairs:Array.isArray(db.repairs)?db.repairs.filter(r=>!r.deletedAt):[],requests:Array.isArray(db.driverRepairRequests)?db.driverRepairRequests.filter(r=>!r.deletedAt):[]}}
function carBy(id,d=data()){return d.cars.find(c=>String(c.id)===String(id))}
function model(c){try{return window.model?.(c)||{brand:c?.brand||'',model:c?.model||''}}catch{return{brand:c?.brand||'',model:c?.model||''}}}
function statusText(s){try{return window.repairStatusText?.(s)||s}catch{return s}}
function activeRepair(r){return !['done','cancelled','rejected','archived','closed'].includes(String(r.status||'').toLowerCase())}
function name(){const c=window.FleetPilotCloud||{},p=c.profile||{};return p.display_name||p.full_name||p.name||c.session?.user?.email||'Механик'}
function kpis(d){const a=d.repairs.filter(activeRepair);return{active:a.length,repair:a.filter(r=>r.status==='repair').length,service:a.filter(r=>r.status==='service').length,parts:a.filter(r=>r.status==='parts').length,newReq:d.requests.filter(r=>['new','accepted'].includes(String(r.status||'').toLowerCase())).length,done:d.repairs.filter(r=>r.status==='done').length}}
function repairRow(r,d){const c=carBy(r.carId,d),m=model(c);return `<article class="ma-row"><div class="ma-car"><strong>${esc(m.brand)} ${esc(m.model)}</strong><small>${esc(c?.plate||'Без номера')} · ${esc(c?.city||'—')}</small></div><div class="ma-task"><strong>${esc(r.title||'Сервисная работа')}</strong><small>${esc(r.problem||r.note||r.service||'')}</small></div><span class="ma-chip ${esc(r.status||'planned')}">${esc(statusText(r.status)||'Без статуса')}</span><div class="ma-actions"><button data-ma-open-repair="${esc(r.id)}">Открыть</button>${activeRepair(r)&&window.serviceNextStatusLabel?.(r.status)?`<button class="primary" data-ma-next="${esc(r.id)}">${esc(window.serviceNextStatusLabel(r.status))}</button>`:''}</div></article>`}
function home(d){const k=kpis(d),active=d.repairs.filter(activeRepair).slice(0,8);return `<header class="ma-head"><div><small>Сервисный отдел</small><h1>Здравствуйте, ${esc(name())}</h1><p>${esc(window.FleetPilotCloud?.workspace?.name||'FleetPilot')}</p></div><button data-ma-tab="profile" class="ma-avatar">🔧</button></header><section class="ma-kpis"><button data-ma-tab="queue"><span>Активные</span><strong>${k.active}</strong></button><button data-ma-filter="repair"><span>В ремонте</span><strong>${k.repair}</strong></button><button data-ma-filter="service"><span>Ждут сервис</span><strong>${k.service}</strong></button><button data-ma-filter="parts"><span>Ждут детали</span><strong>${k.parts}</strong></button><button data-ma-tab="requests"><span>Заявки</span><strong>${k.newReq}</strong></button><button data-ma-filter="done"><span>Выполнено</span><strong>${k.done}</strong></button></section><section class="ma-card"><div class="ma-card-head"><div><small>Рабочая очередь</small><h2>Текущие работы</h2></div><button data-ma-action="new-repair">+ Задача</button></div>${active.length?active.map(r=>repairRow(r,d)).join(''):`<div class="ma-empty">Активных работ нет</div>`}</section>`}
function queue(d,filter=''){let rows=d.repairs.filter(r=>filter==='done'?r.status==='done':activeRepair(r));if(filter&&filter!=='done')rows=rows.filter(r=>r.status===filter);return `<div class="ma-page-head"><div><small>Сервис</small><h1>${filter?esc(statusText(filter)): 'Рабочая очередь'}</h1></div><button data-ma-action="new-repair">+ Новая задача</button></div><section class="ma-card">${rows.length?rows.map(r=>repairRow(r,d)).join(''):`<div class="ma-empty">Записей нет</div>`}</section>`}
function requests(d){const rows=d.requests.filter(r=>!['rejected','cancelled','archived','done'].includes(String(r.status||'').toLowerCase())).slice(0,30);return `<div class="ma-page-head"><div><small>От водителей</small><h1>Новые заявки</h1></div></div><section class="ma-card">${rows.length?rows.map(r=>{const c=carBy(r.car_id||r.carId||r.vehicleId,d),m=model(c);return `<article class="ma-row"><div class="ma-car"><strong>${esc(m.brand)} ${esc(m.model)}</strong><small>${esc(c?.plate||'Без авто')}</small></div><div class="ma-task"><strong>${esc((window.DRIVER_REPAIR_CATEGORY_LABELS||{})[r.category]||r.category||'Заявка')}</strong><small>${esc(r.description||'Без описания')} · ${Number(r.mileage||0).toLocaleString('ru-RU')} км</small></div><span class="ma-chip request">${esc((window.DRIVER_REPAIR_STATUS_LABELS||{})[r.status]||r.status||'new')}</span><div class="ma-actions"><button data-ma-request="${esc(r.id)}">Открыть</button></div></article>`}).join(''):`<div class="ma-empty">Новых заявок нет</div>`}</section>`}
function cars(d){const ids=new Set(d.repairs.filter(activeRepair).map(r=>String(r.carId)));const rows=d.cars.filter(c=>ids.has(String(c.id)));return `<div class="ma-page-head"><div><small>Автомобили</small><h1>Машины в сервисе</h1></div></div><section class="ma-grid">${rows.length?rows.map(c=>{const m=model(c),count=d.repairs.filter(r=>String(r.carId)===String(c.id)&&activeRepair(r)).length;return `<article class="ma-car-card"><div><small>${esc(c.city||'—')}</small><h2>${esc(m.brand)} ${esc(m.model)}</h2><p>${esc(c.plate||'Без номера')}</p></div><strong>${count} задач</strong><button data-ma-open-car="${esc(c.id)}">Открыть автомобиль</button></article>`}).join(''):`<div class="ma-empty">Сейчас машин в сервисе нет</div>`}</section>`}
function calendar(d){const rows=d.repairs.filter(r=>r.date).sort((a,b)=>String(a.date).localeCompare(String(b.date))).slice(0,30);return `<div class="ma-page-head"><div><small>План</small><h1>Календарь сервиса</h1></div><button data-ma-open-page="calendarPage">Полный календарь</button></div><section class="ma-card">${rows.length?rows.map(r=>{const c=carBy(r.carId,d),m=model(c);return `<article class="ma-calendar-row"><time>${esc(r.date||'')}</time><div><strong>${esc(r.title||'Работа')}</strong><small>${esc(m.brand)} ${esc(m.model)} · ${esc(c?.plate||'')}</small></div><span class="ma-chip ${esc(r.status||'planned')}">${esc(statusText(r.status)||'')}</span></article>`}).join(''):`<div class="ma-empty">Запланированных работ нет</div>`}</section>`}
function profile(d){const k=kpis(d),cloud=window.FleetPilotCloud||{};return `<div class="ma-profile"><div class="ma-profile-avatar">🔧</div><h1>${esc(name())}</h1><p>${esc(cloud.session?.user?.email||'')}</p><span>Механик</span></div><section class="ma-card"><div class="ma-profile-grid"><div><small>Компания</small><strong>${esc(cloud.workspace?.name||'—')}</strong></div><div><small>Город</small><strong>${esc(cloud.membership?.city||cloud.workspace?.city||'—')}</strong></div><div><small>Активных работ</small><strong>${k.active}</strong></div><div><small>Выполнено</small><strong>${k.done}</strong></div></div></section><section class="ma-card ma-menu"><button data-ma-action="password">🔐 <span><strong>Безопасность</strong><small>Изменить пароль</small></span></button><button data-ma-action="logout">↪ <span><strong>Выйти</strong><small>Завершить сеанс</small></span></button></section>`}
let filter='';
function render(){if(!mounted)return;const root=$('#fleetPilotMechanicApp');if(!root)return;const d=data();const body=tab==='home'?home(d):tab==='queue'?queue(d,filter):tab==='requests'?requests(d):tab==='cars'?cars(d):tab==='calendar'?calendar(d):profile(d);root.innerHTML=`<aside class="ma-nav"><div class="ma-brand"><b>F</b><span>FleetPilot<small>Сервис</small></span></div><nav><button class="${tab==='home'?'active':''}" data-ma-tab="home">⌂ <span>Главная</span></button><button class="${tab==='queue'?'active':''}" data-ma-tab="queue">🔧 <span>Работы</span></button><button class="${tab==='requests'?'active':''}" data-ma-tab="requests">☷ <span>Заявки</span></button><button class="${tab==='cars'?'active':''}" data-ma-tab="cars">🚗 <span>Автомобили</span></button><button class="${tab==='calendar'?'active':''}" data-ma-tab="calendar">□ <span>Календарь</span></button><button class="${tab==='profile'?'active':''}" data-ma-tab="profile">◎ <span>Профиль</span></button></nav></aside><main class="ma-content">${body}</main>`}
function mount(){if(!isMechanic())return false;let root=$('#fleetPilotMechanicApp');if(!root){root=document.createElement('div');root.id='fleetPilotMechanicApp';document.body.appendChild(root)}document.documentElement.classList.add('fp-mechanic-app');mounted=true;render();return true}
function unmount(){document.documentElement.classList.remove('fp-mechanic-app');$('#fleetPilotMechanicApp')?.remove();mounted=false}
function sync(){isMechanic()?mount():unmount()}
document.addEventListener('click',e=>{const t=e.target.closest('[data-ma-tab]');if(t){tab=t.dataset.maTab;filter='';render();return}const f=e.target.closest('[data-ma-filter]');if(f){tab='queue';filter=f.dataset.maFilter;render();return}const rid=e.target.closest('[data-ma-open-repair]')?.dataset.maOpenRepair;if(rid){window.editRepair?.(rid);return}const next=e.target.closest('[data-ma-next]')?.dataset.maNext;if(next){window.advanceServiceRepair?.(next);render();return}const req=e.target.closest('[data-ma-request]')?.dataset.maRequest;if(req){window.openRepairFromFleetRequest?.(req);return}const car=e.target.closest('[data-ma-open-car]')?.dataset.maOpenCar;if(car){window.openCar?.(car,'service');return}const page=e.target.closest('[data-ma-open-page]')?.dataset.maOpenPage;if(page){window.showPage?.(page);return}const a=e.target.closest('[data-ma-action]')?.dataset.maAction;if(a==='new-repair')window.openRepairDialog?.();if(a==='password')document.getElementById('changePasswordDialog')?.showModal?.();if(a==='logout')window.FleetPilotCloud?.signOut?.()});
['fleetpilot:access-ready','fleetpilot:modules-ready','fleetpilot:repair-requests-changed','fleetpilot:assignments-changed'].forEach(n=>window.addEventListener(n,()=>setTimeout(()=>{sync();if(mounted)render()},0)));window.addEventListener('pageshow',()=>setTimeout(sync,0));setTimeout(sync,300);FP.MechanicApp={mount,render,sync};})();