/* FleetPilot Permission Core V2.1 — centralized role/page/action enforcement */
(()=>{'use strict';
 const FP=window.FleetPilot=window.FleetPilot||{};
 const role=()=>String(window.enterpriseCurrentRole?.()||window.FleetPilotCloud?.role||'user').toLowerCase();
 const owner=()=>['owner','admin','administrator','ceo'].includes(role())||Boolean(window.FleetPilotCloud?.isWorkspaceOwner);
 const can=p=>owner()||(typeof window.enterpriseCan==='function'&&Boolean(window.enterpriseCan(p)));
 const defs={
  cars:[['cars.view','Видеть автомобили'],['cars.create','Добавлять автомобили'],['cars.edit','Редактировать автомобили'],['cars.delete','Удалять автомобили'],['cars.assign','Назначать водителей'],['cars.mileage','Изменять пробег'],['cars.gps','Видеть GPS и карту']],
  finance:[['finance.view','Видеть финансы'],['finance.expenses','Добавлять расходы'],['finance.payments','Редактировать платежи'],['finance.analytics','Видеть прибыль и аналитику']],
  service:[['service.view','Видеть ремонты'],['service.create','Создавать ремонты'],['service.edit','Менять статус ремонта'],['service.photos','Добавлять фотографии'],['service.calendar','Видеть календарь']],
  documents:[['documents.view','Видеть документы'],['documents.create','Добавлять документы'],['documents.delete','Удалять документы'],['documents.contracts','Видеть договоры']],
  company:[['company.team','Видеть команду'],['company.drivers.manage','Управлять водителями и создавать водителей'],['company.invite','Приглашать пользователей'],['company.roles','Менять роли'],['company.permissions','Менять права'],['company.data','Управлять данными и резервными копиями']],
  carProfile:[['car.profile.info','Обзор'],['car.profile.service','Сервис'],['car.profile.finance','Финансы'],['car.profile.documents','Документы'],['car.profile.history','История'],['car.profile.damages','Повреждения'],['car.profile.finance.edit','Финансы: изменять'],['car.profile.documents.edit','Документы: изменять'],['car.profile.service.edit','Сервис: изменять']],
  driver:[['driver.portal','Использовать кабинет водителя'],['driver.tasks','Работать с заявками и заданиями'],['driver.photos','Принимать/возвращать авто с фотоконтролем'],['driver.protocols','Подписывать протоколы']]
 };
 const pageMap={fleetPage:'cars.view',carPage:'cars.view',driversPage:'company.drivers.manage',repairsPage:'service.view',paymentsPage:'finance.view',expensesPage:'finance.view',analyticsPage:'finance.analytics',documentsPage:'documents.view',companyPage:'company.team',dataPage:'company.data',calendarPage:'service.calendar',mobileMapPage:'cars.gps',driverPortalPage:'driver.portal',driverProfilePage:'driver.portal'};
 const actionMap={
  'cars.create':['#headerAdd','[data-quick-action="car"]','[data-create-car]'],
  'cars.edit':['#carSubmitButton','[data-edit-car]'],
  'cars.delete':['[onclick*="deleteCar("]','[data-delete-car]'],
  'cars.assign':['[data-driver-assignment]','[data-assign-driver]','[onclick*="assignDriver"]'],
  'cars.mileage':['#mileageDialog button[type="submit"]','[onclick*="openMileage"]','[data-edit-mileage]'],
  'cars.gps':['[data-open-gps]','[onclick*="openFullFleetMap"]','[data-control-window="gps"] button'],
  'service.create':['#addRepair','[data-quick-action="repair"]','[data-create-repair]'],
  'service.edit':['#repairSubmitButton','[onclick*="editRepair"]','[onclick*="deleteRepair("]','[onclick*="advanceServiceRepair"]','[data-edit-repair]'],
  'service.photos':['[data-repair-photo]','[data-service-photo]'],
  'finance.expenses':['#addExpense','[data-quick-action="expense"]','[onclick*="openExpenseDialog"]'],
  'finance.payments':['#addPayment','[data-quick-action="payment"]','[onclick*="openPaymentDialog"]','[onclick*="openDepositDialog"]'],
  'documents.create':['#addDocument','[data-quick-action="document"]','[onclick*="openDocumentDialog"]'],
  'documents.delete':['[onclick*="deleteDocument("]','[data-delete-document]'],
  'company.drivers.manage':['#createDriverButton','#openCreateDriver','#openCreateDriverDialog','#addDriver','#newDriver','#createDriver','[data-create-driver]','[data-open-create-driver]','[data-edit-driver]','[data-delete-driver]','[data-delete-manual-driver]'],
  'company.invite':['#openInviteMember','#openInviteMemberSecondary'],
  'company.permissions':['[data-company-tab="permissions"]','#saveRolePermissions','#resetRolePermissions'],
  'company.roles':['select[data-enterprise-role]'],
  'company.data':['[data-company-tab="data"]','#createManualSnapshot']
 };
 function installDefinitions(){if(typeof ROLE_PERMISSION_DEFINITIONS!=='object')return;for(const [group,items] of Object.entries(defs)){const target=ROLE_PERMISSION_DEFINITIONS[group]||(ROLE_PERMISSION_DEFINITIONS[group]=[]);const existing=new Set(target.map(x=>x?.[0]));items.forEach(x=>{if(!existing.has(x[0]))target.push(x)})}try{if(typeof ROLE_PERMISSION_LABELS==='object'&&!ROLE_PERMISSION_LABELS.user)ROLE_PERMISSION_LABELS.user='Пользователь'}catch{}}
 function permissionForPage(pageId){if(pageId==='searchPage')return can('cars.view')||can('service.view')||can('documents.view')||can('finance.view');if(pageId==='attentionPage'||pageId==='morePage')return role()!=='driver';const p=pageMap[pageId];return p?can(p):null}
 function wrapPageAccess(){const current=window.enterpriseCanOpen;if(typeof current!=='function'||current.__fpPermissionCoreV21)return;const raw=current.bind(window);const wrapped=function(pageId){if(owner())return raw(pageId);if(role()==='driver'&&!['driverPortalPage','driverProfilePage'].includes(pageId))return false;const enforced=permissionForPage(pageId);if(enforced!==null)return Boolean(enforced);return raw(pageId)};wrapped.__fpPermissionCoreV21=true;wrapped.__raw=raw;window.enterpriseCanOpen=wrapped}
 function setAllowed(el,ok){el.hidden=!ok;el.setAttribute('aria-hidden',String(!ok));if('disabled'in el)el.disabled=!ok}
 function carDialogPermission(el){const on=String(el.getAttribute('onclick')||'');if(!/openCarDialog\s*\(/.test(on))return'';const inside=(on.match(/openCarDialog\s*\(([^)]*)\)/)||[])[1]?.trim()||'';return !inside||inside==="''"||inside==='""'?'cars.create':'cars.edit'}
 function applyActions(){for(const [perm,selectors] of Object.entries(actionMap)){const ok=can(perm);selectors.forEach(sel=>{try{document.querySelectorAll(sel).forEach(el=>setAllowed(el,ok))}catch{}})}document.querySelectorAll('[onclick*="openCarDialog"]').forEach(el=>{const p=carDialogPermission(el);if(p)setAllowed(el,can(p))});document.querySelectorAll('button,a').forEach(el=>{const text=(el.textContent||'').trim().toLowerCase();if(/создать водителя|добавить водителя|новый водитель/.test(text)&&!can('company.drivers.manage'))setAllowed(el,false)})}
 function redirectIfNeeded(){const current=document.querySelector('.page.active')?.id;if(!current||!window.enterpriseCanOpen||window.enterpriseCanOpen(current))return;const order=['fleetPage','driversPage','repairsPage','paymentsPage','expensesPage','documentsPage','calendarPage','analyticsPage','companyPage','dataPage','searchPage','driverPortalPage','driverProfilePage'];const target=order.find(id=>document.getElementById(id)&&window.enterpriseCanOpen(id));if(target)window.showPage?.(target)}
 function applyPages(){wrapPageAccess();try{window.applyEnterpriseAccess?.()}catch{};applyActions();redirectIfNeeded();try{window.FleetPilotDriverManagementPermissions?.apply?.()}catch{};window.dispatchEvent(new CustomEvent('fleetpilot:permission-core-applied',{detail:{role:role()}}))}
 function targetMatches(target,selectors){for(const sel of selectors){try{if(target.matches(sel)||target.closest(sel))return true}catch{}}return false}
 function guardClick(e){const target=e.target?.closest?.('button,a,[role="button"],select');if(!target)return;const carPerm=carDialogPermission(target);if(carPerm&&!can(carPerm)){e.preventDefault();e.stopImmediatePropagation();window.toast?.('Нет доступа к этому действию');return}for(const [perm,selectors] of Object.entries(actionMap))if(targetMatches(target,selectors)&&!can(perm)){e.preventDefault();e.stopImmediatePropagation();window.toast?.('Нет доступа к этому действию');return}const text=(target.textContent||'').trim().toLowerCase();if(/создать водителя|добавить водителя|новый водитель/.test(text)&&!can('company.drivers.manage')){e.preventDefault();e.stopImmediatePropagation();window.toast?.('Нет доступа к управлению водителями')}}
 function guardSubmit(e){const form=e.target,id=String(form?.id||'').toLowerCase(),dialogText=(form?.closest?.('dialog')?.textContent||'').toLowerCase();let required='';if((/driver/.test(id)&&/(create|add|new|invite)/.test(id))||(/водител/.test(dialogText)&&/(создать|добавить|приглас)/.test(dialogText)))required='company.drivers.manage';else if(/car.*form|vehicle.*form/.test(id)){const editing=Boolean(document.querySelector('#carId')?.value);required=editing?'cars.edit':'cars.create'}else if(/repair.*form|service.*form/.test(id)){const editing=Boolean(document.querySelector('#repairId')?.value);required=editing?'service.edit':'service.create'}else if(/expense.*form/.test(id))required='finance.expenses';else if(/payment.*form|deposit.*form/.test(id))required='finance.payments';else if(/document.*form/.test(id))required='documents.create';if(required&&!can(required)){e.preventDefault();e.stopImmediatePropagation();window.toast?.('Нет доступа к этому действию')}}
 function wrapSavePermissions(){const cloud=window.FleetPilotCloud;if(!cloud||typeof cloud.saveRolePermissions!=='function'||cloud.saveRolePermissions.__fpPermissionV21)return;const raw=cloud.saveRolePermissions.bind(cloud);const wrapped=async(...args)=>{const out=await raw(...args);try{if(typeof companyPermissions==='object'&&args[0])companyPermissions[args[0]]=args[1]||{}}catch{};window.dispatchEvent(new CustomEvent('fleetpilot:permissions-changed',{detail:{role:args[0],permissions:args[1]||{}}}));setTimeout(()=>FP.LivePermissions?.refresh?.({force:true}),0);applyPages();return out};wrapped.__fpPermissionV21=true;cloud.saveRolePermissions=wrapped}
 function boot(){installDefinitions();wrapPageAccess();wrapSavePermissions();applyPages();try{renderRolePermissions?.()}catch{}}
 document.addEventListener('click',guardClick,true);document.addEventListener('submit',guardSubmit,true);['fleetpilot:access-ready','fleetpilot:permissions-applied','fleetpilot:permissions-changed','fleetpilot:modules-ready'].forEach(ev=>window.addEventListener(ev,()=>setTimeout(boot,0)));document.addEventListener('DOMContentLoaded',()=>{boot();new MutationObserver(()=>applyActions()).observe(document.body,{subtree:true,childList:true})},{once:true});setInterval(()=>{wrapPageAccess();wrapSavePermissions();applyActions()},5000);FP.PermissionCoreV2={boot,apply:applyPages,can,defs,pageMap};
})();