/* FleetPilot 20 — Driver Assignment
   Owns assignment/unassignment sync and fresh handover cycles. */
(()=>{
 'use strict';
 const FP=window.FleetPilot=window.FleetPilot||{};
 if(FP.DriverAssignment)return;
 const Core=FP.Core,Status=FP.FleetStatus;if(!Core||!Status)throw new Error('FleetPilot Core/Status required');
 const same=Core.same,now=()=>new Date().toISOString();
 const getCar=id=>{try{return typeof window.car==='function'?window.car(String(id)):Core.cars().find(c=>same(c.id,id))}catch{return Core.cars().find(c=>same(c.id,id))}};
 const refresh=carId=>{try{window.renderFleet?.()}catch{}try{window.renderDriversRegistry?.()}catch{}try{FP.FleetBoard?.render?.()}catch{}try{window.renderDesktopCommandKpis?.()}catch{}try{if(carId&&String(window.selectedCarId||'')===String(carId)&&document.querySelector('#carPage')?.classList.contains('active'))window.openCar?.(carId)}catch{}};
 function startCycle(car,uid){car.driverAcceptedAt='';car.driverAcceptedRevision='';car.driverAssignedAt=now();car.driverAssignmentRevision=`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;try{window.addVehicleHandoverAudit?.(car,'assigned',{key:`assigned:${car.driverAssignmentRevision}`,revision:car.driverAssignmentRevision,at:car.driverAssignedAt,driverUserId:uid,driverName:car.driverName||car.tenant||'',driverEmail:car.driverEmail||'',mileage:car.mileage})}catch{}}
 async function rpc(uid,carId){const cloud=window.FleetPilotCloud,cfg=window.FLEETPILOT_CLOUD_CONFIG||{};if(!cloud?.session?.access_token)throw new Error('Сессия Supabase не найдена');if(!cfg.url||!cfg.publishableKey)throw new Error('Supabase недоступен');const response=await fetch(`${cfg.url}/rest/v1/rpc/assign_driver_vehicle`,{method:'POST',headers:{'Content-Type':'application/json','apikey':cfg.publishableKey,'Authorization':`Bearer ${cloud.session.access_token}`},body:JSON.stringify({driver_user_id_value:String(uid),car_id_value:carId?String(carId):null})});if(!response.ok){let detail='';try{detail=(await response.json())?.message||''}catch{}throw new Error(detail||`assign_driver_vehicle HTTP ${response.status}`)}try{return await response.json()}catch{return null}}
 function clear(car){car.driverUserId='';car.driverEmail='';car.driverName='';car.driverPhone='';car.driverAcceptedAt='';car.driverAcceptedRevision='';car.driverAssignedAt='';if(car.driverAssignmentSource==='account'){car.tenant='';car.driverAssignmentSource=''}Status.sync(car)}
 async function assign(uid,carId,options={}){uid=String(uid||'').trim();carId=String(carId||'').trim();if(!uid)throw new Error('Водитель не выбран');if(!carId)throw new Error('Автомобиль не выбран');const target=getCar(carId);if(!target)throw new Error('Автомобиль не найден');const previous=Core.activeCars().filter(c=>same(c.driverUserId,uid));await rpc(uid,carId);for(const c of previous)if(c!==target)clear(c);const sameCycle=same(target.driverUserId,uid)&&Boolean(target.driverAssignmentRevision);target.driverUserId=uid;target.driverAssignmentSource='account';if(options.email)target.driverEmail=options.email;if(options.name){target.driverName=options.name;target.tenant=options.name}if(options.phone)target.driverPhone=options.phone;if(!sameCycle)startCycle(target,uid);Status.sync(target);try{window.save?.()}catch{}Core.emit('driver-assignment-changed',{driverUserId:uid,carId,status:'pending'});refresh(carId);return target}
 async function unassign(uid,carId=''){uid=String(uid||'').trim();const affected=Core.activeCars().filter(c=>(uid&&same(c.driverUserId,uid))||(carId&&same(c.id,carId)));if(uid)await rpc(uid,null);for(const c of affected)clear(c);try{window.save?.()}catch{}Core.emit('driver-assignment-changed',{driverUserId:uid,carId:'',status:'unassigned'});refresh(carId||affected[0]?.id||'');return affected}
 function install(){const cloud=window.FleetPilotCloud;if(cloud&&!cloud.assignDriverVehicle?.__fp20){const bridge=async(uid,carId)=>carId?assign(uid,carId):unassign(uid);bridge.__fp20=true;cloud.assignDriverVehicle=bridge}if(typeof window.assignVehicleDriverUnified==='function'&&!window.assignVehicleDriverUnified.__fp20){const fn=async(uid,carId,options={})=>assign(uid,carId,options);fn.__fp20=true;window.assignVehicleDriverUnified=fn}if(typeof window.unassignVehicleDriverUnified==='function'&&!window.unassignVehicleDriverUnified.__fp20){const fn=async(uid,carId='')=>unassign(uid,carId);fn.__fp20=true;window.unassignVehicleDriverUnified=fn}return Boolean(window.FleetPilotCloud?.assignDriverVehicle?.__fp20)}
 FP.DriverAssignment=Object.freeze({assign,unassign,install,rpc});
 let attempts=0;const timer=setInterval(()=>{attempts++;if(install()||attempts>50)clearInterval(timer)},100);install();
 console.info('FleetPilot 20 driver assignment ready');
})();