/* FleetPilot Driver App — personal mobile workspace */
(()=>{'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const FP=window.FleetPilot=window.FleetPilot||{};let mounted=false,tab='home',loading=false;const state={context:null,service:[],requests:[],notifications:[],ready:false};
function currentRole(){try{return typeof window.enterpriseCurrentRole==='function'?String(window.enterpriseCurrentRole()||'').toLowerCase():String(window.FleetPilotCloud?.role||document.body?.dataset?.enterpriseRole||'').toLowerCase()}catch{return String(window.FleetPilotCloud?.role||'').toLowerCase()}}
function isDriver(){return currentRole()==='driver'}
function assignedCar(){const id=state.context?.car_id;if(id&&typeof window.car==='function'){const local=window.car(String(id));if(local)return local}try{if(typeof window.driverAssignedCar==='function')return window.driverAssignedCar()}catch{}return null}
function ctx(){const cloud=window.FleetPilotCloud||{},p=cloud.profile||{},email=cloud.session?.user?.email||p.email||'',car=assignedCar(),snap=state.context?.vehicle_snapshot||{};const name=(typeof window.driverProfileDisplayName==='function'?window.driverProfileDisplayName():null)||state.context?.driver_name||p.full_name||p.name||car?.driverName||email||'Водитель';return{p,email,car,snap,name}}
function accepted(){const c=assignedCar(),context=state.context||{};if(context.status==='issued'||context.accepted_at)return true;try{return typeof window.driverVehicleIsAlreadyAccepted==='function'?window.driverVehicleIsAlreadyAccepted():Boolean(c?.driverAcceptedAt)}catch{return Boolean(c?.driverAcceptedAt)}}
function modelOf(c,s={}){if(c&&typeof window.model==='function')return window.model(c);return{brand:s.brand||'Автомобиль',model:s.model||''}}
function documents(x){const carId=String(state.context?.car_id||x.car?.id||'');return (window.db?.documents||[]).filter(d=>!d.deletedAt&&(!d.carId||String(d.carId)===carId)).slice(0,8)}
async function refresh(){if(loading||!isDriver())return;loading=true;try{if(window.FleetPilotCloud?.getDriverPortalContext){state.context=await window.FleetPilotCloud.getDriverPortalContext();try{if(typeof driverPortalContext!=='undefined')driverPortalContext=state.context}catch{}try{await window.loadDriverHandoverState?.()}catch{}}const [service,requests,notifications]=await Promise.all([window.FleetPilotCloud?.getDriverServiceFeed?.().catch?.(()=>[])||[],window.FleetPilotCloud?.getMyDriverRepairRequests?.().catch?.(()=>[])||[],window.FleetPilotCloud?.getMyWorkspaceNotifications?.().catch?.(()=>[])||[]]);state.service=Array.isArray(service)?service:[];state.requests=Array.isArray(requests)?requests:[];state.notifications=Array.isArray(notifications)?notifications:[];state.ready=true}catch(e){console.warn('Driver App refresh',e);state.ready=true}finally{loading=false;if(mounted)render()}}
function avatar(name){return esc(String(name||'В').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'В')}
function vehicleCard(x){const c=x.car,s=x.snap;if(!state.context?.car_id)return `<section class="da-empty da-empty-card"><div class="da-empty-icon">🚘</div><h2>Автомобиль не назначен</h2><p>После назначения автомобиль появится здесь автоматически.</p></section>`;const m=modelOf(c,s),display=c||s,mileage=Number(display.mileage||state.context?.mileage||0),ok=accepted();return `<section class="da-vehicle"><div class="da-vehicle-top"><div><small>Назначенный автомобиль</small><h2>${esc(m.brand)} ${esc(m.model)}</h2><p>${esc(display.plate||'Без номера')} · ${esc(display.vin||'VIN не указан')}</p></div><span class="da-live ${ok?'':'pending'}">${ok?'Принят':'Ожидает приёмки'}</span></div><div class="da-mileage"><span>Текущий пробег</span><strong>${mileage.toLocaleString('ru-RU')} км</strong></div><div class="da-handover">${ok?`<button data-da-action="return">↩ Вернуть автомобиль</button>`:`<button class="primary" data-da-action="issue">📸 Принять автомобиль</button>`}<button data-da-action="request">🔧 Сообщить проблему</button></div></section>`}
function serviceList(limit=99){const rows=(state.service||[]).filter(r=>r.status==='done'||r.driver_action_required===true||r.requires_driver===true||r.driver_message||r.appointment_at||r.scheduled_at||r.date).slice(0,limit);return rows.length?rows.map(r=>`<article class="da-service ${r.status==='done'?'done':''}"><div class="da-service-icon">🔧</div><div><strong>${esc(r.title||'Сервис')}</strong><small>${esc((typeof window.repairStatusText==='function'?window.repairStatusText(r.status):r.status)||'')}</small><p>${esc(r.note||'Запланированное обслуживание автомобиля')}</p><em>${r.date?`📅 ${esc(typeof window.date==='function'?window.date(r.date):r.date)}`:'Дата уточняется'}${r.mileage?` · 🧭 ${Number(r.mileage).toLocaleString('ru-RU')} км`:''}</em></div></article>`).join(''):`<div class="da-calm">Для вас сейчас нет действий по сервису.</div>`}
function home(x){const active=(state.service||[]).filter(r=>!['done','cancelled'].includes(String(r.status||''))),notes=state.notifications.slice(0,3);return `<div class="da-greeting"><div><small>Добро пожаловать</small><h1>${esc(x.name)}</h1></div><button class="da-avatar" data-da-tab="profile">${avatar(x.name)}</button></div>${vehicleCard(x)}<section class="da-section"><div class="da-section-head"><h3>Быстрые действия</h3></div><div class="da-actions"><button data-da-action="request"><b>🔧</b><span>Заявка</span></button><button data-da-tab="service"><b>🛠</b><span>Сервис</span></button><button data-da-tab="vehicle"><b>🚗</b><span>Автомобиль</span></button><button data-da-tab="profile"><b>◎</b><span>Профиль</span></button></div></section><section class="da-section"><div class="da-section-head"><h3>Сервисный план</h3><span>${active.length}</span></div>${serviceList(3)}</section><section class="da-section"><div class="da-section-head"><h3>Уведомления</h3><span>${state.notifications.length}</span></div>${notes.length?notes.map(n=>`<article class="da-row"><div><strong>${esc(n.title||'Уведомление')}</strong><small>${esc(n.message||'')}</small></div><span>›</span></article>`).join(''):`<div class="da-calm">Новых уведомлений нет</div>`}</section>`}
function service(){return `<div class="da-page-head"><button data-da-tab="home">‹</button><div><small>Сервис</small><h1>План и работы</h1></div></div><section class="da-section da-section-flat">${serviceList()}</section>`}
function requests(){const rows=state.requests.slice(0,10);return `<div class="da-page-head"><button data-da-tab="home">‹</button><div><small>Сервис</small><h1>Мои заявки</h1></div><button class="da-add" data-da-action="request">＋</button></div><section class="da-section">${rows.length?rows.map(r=>`<article class="da-request"><div><strong>${esc((window.DRIVER_REPAIR_CATEGORY_LABELS||{})[r.category]||r.category||'Заявка')}</strong><small>${esc(r.description||'')} · ${r.created_at?new Date(r.created_at).toLocaleDateString('ru-RU'):''}</small>${r.manager_comment?`<em>${esc(r.manager_comment)}</em>`:''}</div><span class="da-status">${esc((window.DRIVER_REPAIR_STATUS_LABELS||{})[r.status]||r.status||'new')}</span></article>`).join(''):`<div class="da-empty-small">Заявок пока нет.</div>`}</section>`}
function vehicle(x){const docs=documents(x),display=x.car||x.snap;return `<div class="da-page-head"><button data-da-tab="home">‹</button><div><small>Автомобиль</small><h1>Моя машина</h1></div></div>${vehicleCard(x)}${state.context?.car_id?`<section class="da-section"><h3>Информация</h3><div class="da-info"><div><span>Город</span><strong>${esc(display.city||window.FleetPilotCloud?.membership?.city||'—')}</strong></div><div><span>Статус приёмки</span><strong>${accepted()?'Автомобиль принят':'Ожидает приёмки'}</strong></div><div><span>Страховка</span><strong>${esc(display.insurance||'—')}</strong></div><div><span>Техосмотр</span><strong>${esc(display.inspection||'—')}</strong></div></div></section><section class="da-section"><div class="da-section-head"><h3>Документы</h3><span>${docs.length}</span></div>${docs.length?docs.map(d=>`<article class="da-row"><div><strong>${esc(d.name||(typeof window.documentTypeText==='function'?window.documentTypeText(d.type):d.type)||'Документ')}</strong><small>${esc(d.expiry?`до ${d.expiry}`:d.date||'Доступен')}</small></div><span>›</span></article>`).join(''):`<div class="da-calm">Документов пока нет</div>`}</section>`:''}`}
function profile(x){const display=x.car||x.snap;return `<div class="da-profile-hero"><div class="da-profile-avatar">${avatar(x.name)}</div><h1>${esc(x.name)}</h1><p>${esc(x.email)}</p><span>Водитель</span></div><section class="da-section"><div class="da-info da-profile-info"><div><span>Компания</span><strong>${esc(window.FleetPilotCloud?.workspace?.name||'—')}</strong></div><div><span>Город</span><strong>${esc(display.city||window.FleetPilotCloud?.membership?.city||window.FleetPilotCloud?.workspace?.city||'—')}</strong></div><div><span>Автомобиль</span><strong>${esc(display.plate||'Не назначен')}</strong></div><div><span>Статус</span><strong>${state.context?.car_id?(accepted()?'Автомобиль принят':'Ожидает приёмки'):'Без автомобиля'}</strong></div><div><span>Пробег</span><strong>${state.context?.car_id?`${Number(display.mileage||state.context?.mileage||0).toLocaleString('ru-RU')} км`:'—'}</strong></div><div><span>Заявок</span><strong>${state.requests.length}</strong></div></div></section><section class="da-section"><div class="da-section-head"><h3>Связанный автомобиль</h3></div>${state.context?.car_id?`<article class="da-row" data-da-tab="vehicle"><div><strong>${esc(modelOf(x.car,x.snap).brand)} ${esc(modelOf(x.car,x.snap).model)}</strong><small>${esc(display.plate||'—')} · ${accepted()?'Принят':'Требует приёмки'}</small></div><span>›</span></article>`:`<div class="da-calm">Автомобиль пока не назначен</div>`}</section><section class="da-section da-menu"><button data-da-action="password"><span>🔐</span><div><strong>Безопасность</strong><small>Изменить пароль</small></div><b>›</b></button><button data-da-action="logout"><span>↪</span><div><strong>Выйти</strong><small>Завершить сеанс</small></div><b>›</b></button></section>`}
function loadingView(){return `<div class="da-loading"><div class="da-loading-mark">F</div><strong>Загружаем ваш профиль</strong><small>Подключаем автомобиль, сервис и заявки…</small></div>`}
function render(){if(!mounted)return;const root=$('#fleetPilotDriverApp');if(!root)return;if(!state.ready){root.innerHTML=loadingView();return}const x=ctx(),body=tab==='home'?home(x):tab==='service'?service():tab==='requests'?requests():tab==='vehicle'?vehicle(x):profile(x);root.innerHTML=`<main class="da-content">${body}</main><nav class="da-nav"><button class="${tab==='home'?'active':''}" data-da-tab="home"><span>⌂</span><small>Главная</small></button><button class="${tab==='service'?'active':''}" data-da-tab="service"><span>🔧</span><small>Сервис</small></button><button class="${tab==='requests'?'active':''}" data-da-tab="requests"><span>☷</span><small>Заявки</small></button><button class="${tab==='vehicle'?'active':''}" data-da-tab="vehicle"><span>🚗</span><small>Авто</small></button><button class="${tab==='profile'?'active':''}" data-da-tab="profile"><span>◎</span><small>Профиль</small></button></nav>`}
function mount(){if(!isDriver()||window.innerWidth>1099)return false;let root=$('#fleetPilotDriverApp');if(!root){root=document.createElement('div');root.id='fleetPilotDriverApp';document.body.appendChild(root)}document.documentElement.classList.add('fp-driver-app');document.documentElement.classList.remove('fp-driver-booting','fp-role-loading');mounted=true;render();refresh();return true}
function unmount(){document.documentElement.classList.remove('fp-driver-app','fp-driver-booting');$('#fleetPilotDriverApp')?.remove();mounted=false}
function sync(){if(isDriver()&&window.innerWidth<1100)mount();else unmount()}
document.addEventListener('click',e=>{const t=e.target.closest('[data-da-tab]');if(t){tab=t.dataset.daTab;render();return}const a=e.target.closest('[data-da-action]')?.dataset.daAction;if(a==='request')window.openDriverRepairDialog?.();if(a==='issue')window.openVehicleHandover?.('issue');if(a==='return')window.openVehicleHandover?.('return');if(a==='password')document.getElementById('changePasswordDialog')?.showModal?.();if(a==='logout')window.FleetPilotCloud?.signOut?.()});
['fleetpilot:access-ready','fleetpilot:driver-assignment-changed','fleetpilot:assignments-changed','fleetpilot:repair-requests-changed','fleetpilot:cloud-ready','fleetpilot:modules-ready'].forEach(n=>window.addEventListener(n,()=>setTimeout(()=>{sync();refresh()},0)));window.addEventListener('resize',sync);window.addEventListener('pageshow',()=>setTimeout(()=>{sync();refresh()},0));document.addEventListener('DOMContentLoaded',()=>setTimeout(sync,0));FP.DriverApp={mount,render,sync,refresh,currentRole,state};})();