/* FleetPilot Driver App — personal mobile workspace */
(()=>{'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const FP=window.FleetPilot=window.FleetPilot||{};let mounted=false,tab='home';
function isDriver(){return String(window.FleetPilotCloud?.profile?.role||'').toLowerCase()==='driver'}
function ctx(){const p=window.FleetPilotCloud?.profile||{},uid=String(p.user_id||p.id||window.FleetPilotCloud?.user?.id||''),email=p.email||window.FleetPilotCloud?.user?.email||'';const cars=(window.db?.cars||[]).filter(c=>!c.archived&&!c.deletedAt);const car=cars.find(c=>String(c.driverUserId||'')===uid)||cars.find(c=>String(c.driverEmail||'').toLowerCase()===String(email).toLowerCase())||null;const name=p.display_name||p.full_name||p.name||car?.driverName||car?.tenant||email||'Водитель';return{p,uid,email,car,name}}
function requests(c){if(!c)return[];const id=String(c.id);return (window.db?.driverRepairRequests||window.db?.driverRequests||[]).filter(x=>String(x.carId||x.car_id||x.vehicleId||'')===id&&!x.deletedAt).sort((a,b)=>Date.parse(b.createdAt||b.created_at||0)-Date.parse(a.createdAt||a.created_at||0))}
function avatar(name){return esc(String(name||'В').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'В')}
function vehicleCard(c){if(!c)return `<section class="da-empty"><div class="da-empty-icon">🚘</div><h2>Автомобиль не назначен</h2><p>Когда компания назначит автомобиль, он появится здесь автоматически.</p></section>`;const m=typeof window.model==='function'?window.model(c):{brand:c.brand||'',model:c.model||''};return `<section class="da-vehicle"><div class="da-vehicle-top"><div><small>Ваш автомобиль</small><h2>${esc(m.brand)} ${esc(m.model)}</h2><p>${esc(c.plate||'Без номера')}</p></div><span class="da-live">На линии</span></div><div class="da-mileage"><span>Текущий пробег</span><strong>${Number(c.mileage||0).toLocaleString('ru-RU')} км</strong></div><button class="da-primary" data-da-action="request">Сообщить о проблеме</button></section>`}
function home(x){const rs=requests(x.car),active=rs.filter(r=>!['done','rejected','cancelled','archived'].includes(String(r.status||'').toLowerCase()));return `<div class="da-greeting"><div><small>Добро пожаловать</small><h1>${esc(x.name)}</h1></div><button class="da-avatar" data-da-tab="profile">${avatar(x.name)}</button></div>${vehicleCard(x.car)}<section class="da-section"><div class="da-section-head"><h3>Быстрые действия</h3></div><div class="da-actions"><button data-da-action="request"><b>🔧</b><span>Заявка</span></button><button data-da-tab="vehicle"><b>🚗</b><span>Автомобиль</span></button><button data-da-tab="requests"><b>☷</b><span>Мои заявки</span></button><button data-da-tab="profile"><b>◎</b><span>Профиль</span></button></div></section><section class="da-section"><div class="da-section-head"><h3>Сейчас</h3><span>${active.length}</span></div>${active.length?active.slice(0,3).map(r=>`<article class="da-row"><div><strong>${esc(r.title||r.description||'Заявка в сервис')}</strong><small>${esc(r.status||'new')}</small></div><span>›</span></article>`).join(''):`<div class="da-calm">Активных заявок нет</div>`}</section>`}
function vehicle(x){return `<div class="da-page-head"><button data-da-tab="home">‹</button><div><small>Автомобиль</small><h1>Моя машина</h1></div></div>${vehicleCard(x.car)}${x.car?`<section class="da-section"><h3>Информация</h3><div class="da-info"><div><span>Город</span><strong>${esc(x.car.city||'—')}</strong></div><div><span>Принят</span><strong>${x.car.driverAcceptedAt?'Да':'Ожидает подтверждения'}</strong></div><div><span>Страховка</span><strong>${esc(x.car.insurance||'—')}</strong></div><div><span>Техосмотр</span><strong>${esc(x.car.inspection||'—')}</strong></div></div></section>`:''}`}
function reqs(x){const rs=requests(x.car);return `<div class="da-page-head"><button data-da-tab="home">‹</button><div><small>История</small><h1>Мои заявки</h1></div><button class="da-add" data-da-action="request">＋</button></div><section class="da-section">${rs.length?rs.slice(0,10).map(r=>`<article class="da-request"><div><strong>${esc(r.title||r.description||'Заявка')}</strong><small>${new Date(r.createdAt||r.created_at||Date.now()).toLocaleDateString('ru-RU')}</small></div><span class="da-status">${esc(r.status||'new')}</span></article>`).join(''):`<div class="da-empty-small">Вы ещё не отправляли заявок.</div>`}</section>`}
function profile(x){return `<div class="da-profile-hero"><div class="da-profile-avatar">${avatar(x.name)}</div><h1>${esc(x.name)}</h1><p>${esc(x.email)}</p><span>Водитель</span></div><section class="da-section"><div class="da-info da-profile-info"><div><span>Телефон</span><strong>${esc(x.p.phone||x.car?.driverPhone||'Не указан')}</strong></div><div><span>Город</span><strong>${esc(x.p.city||x.car?.city||'—')}</strong></div><div><span>Автомобиль</span><strong>${esc(x.car?.plate||'Не назначен')}</strong></div><div><span>Заявок</span><strong>${requests(x.car).length}</strong></div></div></section><section class="da-section da-menu"><button data-da-action="password"><span>🔐</span><div><strong>Безопасность</strong><small>Изменить пароль</small></div><b>›</b></button><button data-da-action="logout"><span>↪</span><div><strong>Выйти</strong><small>Завершить сеанс</small></div><b>›</b></button></section>`}
function render(){if(!mounted)return;const root=$('#fleetPilotDriverApp'),x=ctx();root.innerHTML=`<main class="da-content">${tab==='home'?home(x):tab==='vehicle'?vehicle(x):tab==='requests'?reqs(x):profile(x)}</main><nav class="da-nav"><button class="${tab==='home'?'active':''}" data-da-tab="home"><span>⌂</span><small>Главная</small></button><button class="${tab==='requests'?'active':''}" data-da-tab="requests"><span>☷</span><small>Заявки</small></button><button class="${tab==='vehicle'?'active':''}" data-da-tab="vehicle"><span>🚗</span><small>Авто</small></button><button class="${tab==='profile'?'active':''}" data-da-tab="profile"><span>◎</span><small>Профиль</small></button></nav>`}
function mount(){if(!isDriver()||window.innerWidth>1099)return false;let root=$('#fleetPilotDriverApp');if(!root){root=document.createElement('div');root.id='fleetPilotDriverApp';document.body.appendChild(root)}document.documentElement.classList.add('fp-driver-app');mounted=true;render();return true}
function unmount(){document.documentElement.classList.remove('fp-driver-app');$('#fleetPilotDriverApp')?.remove();mounted=false}
document.addEventListener('click',e=>{const t=e.target.closest('[data-da-tab]');if(t){tab=t.dataset.daTab;render();return}const a=e.target.closest('[data-da-action]')?.dataset.daAction;if(a==='request'){window.openDriverRepairDialog?.();document.getElementById('driverRepairDialog')?.showModal?.()}if(a==='password')document.getElementById('changePasswordDialog')?.showModal?.();if(a==='logout')window.FleetPilotCloud?.signOut?.()});
['fleetpilot:access-ready','fleetpilot:driver-assignment-changed','fleetpilot:cloud-ready'].forEach(n=>window.addEventListener(n,()=>setTimeout(()=>isDriver()?mount():unmount(),0)));window.addEventListener('resize',()=>isDriver()?(window.innerWidth<1100?mount():unmount()):unmount());window.addEventListener('pageshow',()=>setTimeout(mount,0));setTimeout(mount,300);FP.DriverApp={mount,render};})();